"use client";

import {
  Dialog,
  DialogContent,
} from "@/components/ui/dialog";

interface ReportDetail {
  reportId: string;
  phoneNumber: string;
  status: string;
  individual: string;
  generatedBy: string;
  role: string;
  reportType: string;
  createdDate: string;
  lastUpdated: string;
}

interface ReportViewModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: ReportDetail | null;
}

const Field = ({ label, value }: { label: string; value: string }) => (
  <div>
    <p className="text-xs font-normal text-[#6B7280]">{label}</p>
    <p className="mt-0.5 text-sm font-semibold text-[#111827]">{value || "N/A"}</p>
  </div>
);

export default function ReportViewModal({ isOpen, onClose, report }: ReportViewModalProps) {
  if (!report) return null;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-[420px] rounded-[12px] bg-white p-6">
        {/* Report ID */}
        <div className="mb-4 text-center">
          <p className="text-xs font-normal text-[#6B7280]">Report Id</p>
          <p className="text-base font-bold text-[#111827]">{report.reportId}</p>
        </div>

        <div className="grid grid-cols-2 gap-x-6 gap-y-4">
          <Field label="Phone Number"  value={report.phoneNumber} />
          <Field label="Status"        value={report.status} />
          <Field label="Individual"    value={report.individual} />
          <Field label="Generated By"  value={report.generatedBy} />
          <Field label="Role"          value={report.role} />
          <Field label="Report Type"   value={report.reportType} />
          <Field label="Created Date"  value={report.createdDate} />
          <Field label="Last Updated"  value={report.lastUpdated} />
        </div>
      </DialogContent>
    </Dialog>
  );
}
